### ISSUE TITLE
image_translator final presentation date

### ISSUE THREAD

**Issue by YuchengMaUTK** [CS340-19/news#9]
17th
19th
22nd

**Comment by audrism** [comment]
@YuchengMaUTK  
I checked and there is no class on 19th: I moved you to 17th if that works for you. Please let me know.

**Comment by YuchengMaUTK** [comment]
Hi Dr. Mockus,
Thank you for let us know this. I am ok for tommorrw but I need double check it with my teammates. Can we reply you latter after we have a meeting?
Thank you so much, have a good day.

在 2019年4月16日，上午7:23，Audris Mockus <notifications@github.com<mailto:notifications@github.com>> 写道：


@YuchengMaUTK<https://github.com/YuchengMaUTK>
I checked and there is no class on 19th: I moved you to 17th if that works for you. Please let me know.

**Comment by YuchengMaUTK** [comment]
Hi Dr. Mockus,
Thank you for letting us know this. I am ok to move the presentation to tommorrow but I need to tell my teammates and ask them if it is ok for them. Can I reply you latter after I asked them. Thank you so much.
Have a good day!

在 2019年4月16日，上午7:23，Audris Mockus <notifications@github.com<mailto:notifications@github.com>> 写道：


@YuchengMaUTK<https://github.com/YuchengMaUTK>
I checked and there is no class on 19th: I moved you to 17th if that works for you. Please let me know.
